cd Flarum
composer require flarum-lang/chinese-simplified
composer require askvortsov/flarum-auto-moderator
composer require antoinefr/flarum-ext-bbcode-fa
composer require fof/default-group
composer require fof/doorman
composer require fof/formatting
composer require fof/links
composer require fof/nightmode
composer require fof/pages
composer require fof/pretty-mail
composer require fof/profile-image-crop
composer require fof/terms
composer require fof/upload
composer require blomstra/fontawesome
composer require afrux/forum-stats-widget
composer require askvortsov/flarum-moderator-warnings
composer require afrux/online-users-widget
composer require sycho/flarum-profile-cover
composer require v17development/flarum-seo
composer require ganuonglachanh/flarum-ext-search
composer require justoverclock/username-blacklist
composer require v17development/flarum-user-badges
composer require yannisme/oxotheme
composer require ffans/clipboardjs
composer require fof/sitemap
composer require fof/ban-ips
composer require fof/disposable-emails
composer require fof/cookie-consent
composer require fof/github-autolink
composer require nomiscz/flarum-ext-auth-wechat
composer require nyu8/flarum-email-filter
composer require clarkwinkelmann/flarum-ext-who-read
composer require afrux/top-posters-widget:"*"
